GET http://localhost:3000

###
GET http://localhost:3000/trial

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "NNNvvvefed@gmail.com",
    "password":"3334"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "NNNvvvefed@gmail.com",
    "password":"3334"
}

###
DELETE http://localhost:3000/auth/logout